:- module(game_over_screen, [print_game_over/0]).

print_game_over :-
    nl,
    write('┌────────────────────────────────────────────────────────────────────┐'), nl,
    write('│                                                                    │'), nl,
    write('│                           GAME OVER                                │'), nl,
    write('│                                                                    │'), nl,
    write('│  ██   ██  █████   ██████ ██   ██ ██ ███    ██  ██████               │'), nl,
    write('│  ██   ██ ██   ██ ██      ██  ██  ██ ████   ██ ██                    │'), nl,
    write('│  ███████ ███████ ██      █████   ██ ██ ██  ██ ██   ███              │'), nl,
    write('│  ██   ██ ██   ██ ██      ██  ██  ██ ██  ██ ██ ██    ██              │'), nl,
    write('│  ██   ██ ██   ██  ██████ ██   ██ ██ ██   ████  ██████               │'), nl,
    write('│                                                                    │'), nl,
    write('│            ██ ███████     ███    ██  ██████  ███████                │'), nl,
    write('│            ██ ██          ████   ██ ██    ██    ██                  │'), nl,
    write('│            ██ ███████     ██ ██  ██ ██    ██    ██                  │'), nl,
    write('│            ██      ██     ██  ██ ██ ██    ██    ██                  │'), nl,
    write('│            ██ ███████     ██   ████  ██████     ██                  │'), nl,
    write('│                                                                    │'), nl,
    write('│                    ██      ██    ██  ██████  ██   ██                │'), nl,
    write('│                    ██      ██    ██ ██      ██  ██                 │'), nl,
    write('│                    ██      ██    ██ ██      █████                  │'), nl,
    write('│                    ██      ██    ██ ██      ██  ██                 │'), nl,
    write('│                    ███████  ██████   ██████ ██   ██                │'), nl,
    write('│                                                                    │'), nl,
    write('│                         Made by:                                   │'), nl,
    write('│                     Guilherme Noronha                              │'), nl,
    write('│                     João Ventura                                   │'), nl,
    write('│                     Lucas Cunha                                    │'), nl,
    write('│                     Matteus Marinho                                │'), nl,
    write('│                     Pedro Trovão                                   │'), nl,
    write('│                                                                    │'), nl,
    write('└────────────────────────────────────────────────────────────────────┘'), nl,
    nl.